baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Ken Shirts'
theme = 'PaperMod'



[[menu.main]]
identifier = "categories"
name = "Artists"
url = "/categories/"


[[menu.main]]
identifier = "tags"
name = "Manufacturers"
url = "/tags/"

[[menu.main]]
identifier = "search"
name = "Search"
url="/search/"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = [ "title", "permalink", "summary", "content" ]

